steps:
- id: "Build Container Image"
  name: nixos/nix
  entrypoint: bash
  secretEnv: ['CACHIX_AUTH_TOKEN']
  args:
    - -c
    - |
      set -exuo pipefail

      # Install nix deps
      echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      nix-env -iA nixpkgs.nixUnstable nixpkgs.git nixpkgs.cacert nixpkgs.jq
      git config --global init.defaultBranch main

      # Configure cachix
      nix-env -iA cachix -f https://cachix.org/api/v1/install
      cachix use hosscoinbot

      # Build & Cache
      cachix watch-exec hosscoinbot nix build .#hosscoinbotImage
      
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['load', '-i', './result']
  volumes:
  - name: nix-store
    path: /nix/
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'hosscoinbot:$COMMIT_SHA', 'us-east4-docker.pkg.dev/$PROJECT_ID/hosscoinbot/hosscoinbot:$COMMIT_SHA']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/cachix-write-token/versions/latest
    env: 'CACHIX_AUTH_TOKEN'

images:
- us-east4-docker.pkg.dev/$PROJECT_ID/hosscoinbot/hosscoinbot
timeout: 900s